# Generated by Django 5.1.5 on 2025-02-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gluten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gluten', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='crust',
            name='gluten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_Place.gluten'),
        ),
    ]
