# Generated by Django 5.1.5 on 2025-02-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0002_gluten_alter_crust_gluten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crust',
            name='gluten',
        ),
        migrations.AddField(
            model_name='pizza',
            name='gluten',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_Place.gluten'),
            preserve_default=False,
        ),
    ]
