# Generated by Django 5.1.5 on 2025-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0003_remove_pizza_toppings_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizza_Place.topping'),
        ),
    ]
