# Generated by Django 5.1.5 on 2025-02-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0003_remove_crust_gluten_pizza_gluten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('card_number', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('card_expiry', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='order_number',
            new_name='id',
        ),
    ]
