# Generated by Django 5.1.5 on 2025-02-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0003_crust_pizza_size_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
