# Generated by Django 5.1.5 on 2025-02-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0004_payment_details_rename_order_number_pizza_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_details',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='customer_id',
        ),
    ]
