# Generated by Django 5.1.5 on 2025-02-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0005_remove_payment_details_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizza_Place.topping'),
        ),
    ]
