# Generated by Django 5.1.5 on 2025-02-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0006_alter_pizza_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
