# Generated by Django 5.1.5 on 2025-02-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0007_delete_customer_alter_pizza_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_Place.topping'),
        ),
    ]
