# Generated by Django 5.1.5 on 2025-02-17 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0008_alter_topping_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='OrderedPizza',
        ),
    ]
