# Generated by Django 5.1.5 on 2025-02-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0009_rename_id_pizza_ordernumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='ordernumber',
            new_name='id',
        ),
    ]
