# Generated by Django 5.1.5 on 2025-02-17 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0009_rename_pizza_orderedpizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedpizza',
            name='ordertime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
