# Generated by Django 5.1.5 on 2025-02-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0010_rename_ordernumber_pizza_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='id',
            new_name='ordernumber',
        ),
    ]
