# Generated by Django 5.1.5 on 2025-02-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0011_orderedpizza_deliverytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_details',
            name='address',
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
