# Generated by Django 5.1.5 on 2025-02-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0012_pizza_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='ordernumber',
            new_name='id',
        ),
    ]
