# Generated by Django 5.1.5 on 2025-02-13 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0013_rename_ordernumber_pizza_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cvv',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
