# Generated by Django 5.1.5 on 2025-02-13 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0014_alter_payment_details_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='card_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
