# Generated by Django 5.1.5 on 2025-02-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0015_alter_payment_details_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='cheese',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='crust',
            old_name='thickness',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gluten',
            old_name='gluten',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sauce',
            old_name='sauce',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='name',
        ),
    ]
