# Generated by Django 5.1.5 on 2025-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_Place', '0016_rename_cheese_cheese_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
